import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import type { Metadata } from "next";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const juniCode = localFont({
  src: [
    {
      path: "../public/Fonts/JuniCode/Junicode-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/Fonts/JuniCode/Junicode.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-juniCode",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${juniCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
